version: "3.9"
services:
  api:
    image: sobolt/hortivation-hub-datasource-api:${VERSION_TAG:-latest}
    container_name: hor-datasource-api
    restart: always
    environment:
      - HUB_PORTAL=${HUB_PORTAL:-https://hub.hortivation.cloud}
      - FUSEKI_HOST=${FUSEKI_HOST:-http://fuseki:3030}
      - FUSEKI_USER=${FUSEKI_USER:-admin}
      - FUSEKI_PW=${FUSEKI_PW}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.routers.api.rule=Host(`${HOSTNAME:-localhost}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=lets-encrypt"
    volumes:
      - "file-data:/datasets"
      - "dataset-descriptions:/descriptions"
    secrets:
      - credentials

  traefik:
    image: docker.io/traefik:v2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.lets-encrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.lets-encrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt

  discovery:
    image: sobolt/hortivation-hub-datasource-discovery:${VERSION_TAG:-latest}
    container_name: hor-datasource-discovery
    environment:
      - HUB_PORTAL=${HUB_PORTAL:-https://hub.hortivation.cloud}
      - FUSEKI_HOST=${FUSEKI_HOST:-http://fuseki:3030}
      - FUSEKI_USER=${FUSEKI_USER:-admin}
      - FUSEKI_PW=${FUSEKI_PW}
    volumes:
      - "file-data:/datasets"
      - "dataset-descriptions:/descriptions"
      - "${CONFIG_PATH:-./datasource_description.yaml}:/discovery/datasource_description.yaml"
    secrets:
      - credentials

  fuseki:
    image: sobolt/hortivation-hub-datasource-fuseki:${VERSION_TAG:-latest}
    container_name: hor-datasource-fuseki
    environment:
      - ADMIN_PASSWORD=${FUSEKI_PW}
      - TDB=2
    volumes:
      - "fuseki-data:/fuseki"
    ports:
      - "3030:3030"
  
  # frontend:
  #   image: sobolt/hortivation-hub-datasource-frontend:${VERSION_TAG:-latest}
  #   container_name: hor-frontend
  #   restart: always
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.frontend.loadbalancer.server.port=80"
  #     - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME:-localhost}`) && PathPrefix(`/dashboard/`)"
  #     - "traefik.http.routers.frontend.middlewares=frontend-stripprefix"
  #     - "traefik.http.middlewares.frontend-stripprefix.stripprefix.prefixes=/dashboard"
  #     - "traefik.http.routers.frontend.entrypoints=web"
  #     - "traefik.http.routers.frontend.entrypoints=websecure"
  #     - "traefik.http.routers.frontend.tls.certresolver=lets-encrypt"

volumes:
  letsencrypt:
  dataset-descriptions:
  file-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./datasets
  fuseki-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.fuseki

secrets:
  credentials:
    file: ./ADD_FILEPATH_HERE
